---
- name: System Initialization
  hosts: "{{ host | default('localhost') }}"
  become: true
  gather_facts: true
  vars:
    upgrade: true
    github_token: "{{ vault_github_token | default('') }}"
  roles:
    - sysinit
