---
- name: dbeaver - Exists
  ansible.builtin.stat:
    path: /usr/bin/dbeaver
  register: dbeaver_exists_result

- name: dbeaver - Install/Upgrade
  ansible.builtin.apt:
    deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
  when: dbeaver_exists_result.stat.exists == false or upgrade == true
