---
- name: Check for docker gpg file
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: "Add docker official GPG key for {{ ansible_distribution }}"
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    keyring: "/etc/apt/keyrings/docker.gpg"
  when: not docker_gpg.stat.exists

- name: Fix keyring permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}/
      {{ ansible_distribution_release }} stable
    state: present

- name: Docker - Install
  ansible.builtin.apt:
    pkg:
      - bash-completion
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

- name: Docker - Add docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker - Configure user
  ansible.builtin.user:
    name: "{{ user_item }}"
    groups: docker
    append: true
  loop_control:
    loop_var: user_item
  loop:
    - "{{ lookup('env', 'USER') }}"

- name: Docker - Install completion
  block:
    - name: Docker - Get completion script content for checksum calculation
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
        method: GET
        return_content: true
      register: docker_completion_content

    - name: Docker - Calculate checksum of completion script
      ansible.builtin.set_fact:
        docker_completion_sha256: "{{ docker_completion_content.content | hash('sha256') }}"
      when: docker_completion_content is succeeded

    - name: Docker - Download completion script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
        dest: /etc/bash_completion.d/docker.sh
        mode: +x
        checksum: "{{ 'sha256:' + docker_completion_sha256 if docker_completion_sha256 is defined else omit }}"
