---
- name: Mise - Set mise path
  ansible.builtin.set_fact:
    mise_path: "/home/{{ lookup('env', 'USER') }}/.local/bin"

- name: Mise - Set mise binary
  ansible.builtin.set_fact:
    mise_bin: "{{ mise_path }}/mise"

- name: Mise - Check if mise exists
  ansible.builtin.stat:
    path: "{{ mise_bin }}"
  register: mise_exists_result

- name: Mise - Install
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  when: not mise_exists_result.stat.exists or upgrade | default(false)
  block:
    - name: Mise - Create local bin directory
      ansible.builtin.file:
        path: "{{ mise_path }}"
        state: directory
        mode: "0755"

    - name: Mise - Import gpg key
      ansible.builtin.shell: >
        gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0x7413A06D
      args:
        creates: "/home/{{ lookup('env', 'USER') }}/.gnupg/pubring.kbx"

    - name: Mise - Download signed install script
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/install.sh.sig
        dest: "/tmp/mise-install.sh.sig"
        mode: "0644"

    - name: Mise - Verify and extract install script
      ansible.builtin.shell: >
        set -o pipefail &&
        gpg --decrypt /tmp/mise-install.sh.sig > /tmp/mise-install.sh
      args:
        creates: "/tmp/mise-install.sh"

    - name: Mise - Make install script executable
      ansible.builtin.file:
        path: "/tmp/mise-install.sh"
        mode: "0755"

    - name: Mise - Run install script
      ansible.builtin.shell: >
        export MISE_INSTALL_PATH="{{ mise_path }}" &&
        /tmp/mise-install.sh
      args:
        creates: "{{ mise_bin }}"

    - name: Mise - Clean up temporary files
      ansible.builtin.file:
        path: "{{ cleanup_item }}"
        state: absent
      loop_control:
        loop_var: cleanup_item
      loop:
        - "/tmp/mise-install.sh.sig"
        - "/tmp/mise-install.sh"

- name: Mise - Install plugins
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Mise - Install custom plugins
      ansible.builtin.shell: >
        {{ mise_bin }} plugin add {{ custom_plugin_item.plugin }} {{ custom_plugin_item.src }}
      args:
        creates: "$HOME/.local/share/mise/plugins/{{ custom_plugin_item.plugin }}"
      loop_control:
        loop_var: custom_plugin_item
      loop: "{{ sysinit_mise_custom_plugins }}"
      when: sysinit_mise_custom_plugins is defined and sysinit_mise_custom_plugins | length > 0

    - name: Mise - Install default plugins
      ansible.builtin.shell: >
        {{ mise_bin }} use -g -y {{ plugin_item }}
      args:
        creates: "$HOME/.local/share/mise/plugins/{{ plugin_item }}"
      loop_control:
        loop_var: plugin_item
      loop: "{{ sysinit_mise_plugins }}"
      when: sysinit_mise_plugins is defined and sysinit_mise_plugins | length > 0
