---
- name: Display system info
  ansible.builtin.debug:
    msg:
      - "User: {{ ansible_user_id }}"
      - "User Home: {{ ansible_env.HOME }}"
      - "Sudo User: {{ lookup('env', 'USER') }}"
      - "Sudo User: {{ ansible_env.SUDO_HOME }}"
      - "System: {{ ansible_system }}"
      - "Architecture: {{ ansible_userspace_architecture }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Release: {{ ansible_distribution_release }}"
      - "Sysinit: {{ sysinit_var }}"

- name: Load variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Install system packages
  ansible.builtin.package:
    name: "{{ sysinit_packages }}"
    state: present

- name: Install Debian / Ubuntu community or private packages
  ansible.builtin.include_tasks: "apt.yml"
  loop: "{{ sysinit_apt_packages | default([]) }}"
  when: ansible_distribution == 'Debian'

- name: Install Arch aur packages
  ansible.builtin.include_tasks: "aur.yml"
  when: ansible_distribution == 'Archlinux'

- name: Install tools
  ansible.builtin.include_tasks: "tools/{{ item }}.yml"
  loop: "{{ combined_tools | default([]) }}"
  when: combined_tools is defined and combined_tools | length > 0
