---
packages:
  - apt-transport-https
  - blueman
  - bluetooth
  - build-essential
  - ca-certificates
  - dnsutils
  - libffi-dev
  - libnss3-tools
  - libbz2-dev
  - liblzma-dev
  - libncursesw5-dev
  - libreadline-dev
  - libssl-dev
  - libsqlite3-dev
  - libxml2-dev
  - libxmlsec1-dev
  - stow
  - tk-dev
  - xsel
  - xz-utils
  - zlib1g-dev

tools:
  - aws-ssm
  - docker
  - mise
  - opass
